"""Generate the action reference from bundled descriptors and map metadata."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from google.protobuf import descriptor_pb2
from recovered_replay import SCHEMA, load_catalog, load_catalog_corpus, varint


def generate():
    schema = descriptor_pb2.FileDescriptorProto()
    schema.ParseFromString(SCHEMA.read_bytes())
    messages = {m.name: m for m in schema.message_type}
    extensions = {e.number: e.name for e in schema.extension}

    def flags(message):
        raw, pos, result = message.options.SerializeToString(), 0, []
        while pos < len(raw):
            key, pos = varint(raw, pos)
            if key & 7:
                raise ValueError('Unexpected option wire type')
            value, pos = varint(raw, pos)
            if value:
                result.append(extensions.get(key >> 3, str(key >> 3)))
        return ', '.join(result)

    def fields(message):
        output = []
        for f in message.field:
            kind = f.type_name.rsplit('.', 1)[-1] if f.type_name else descriptor_pb2.FieldDescriptorProto.Type.Name(f.type).removeprefix('TYPE_').lower()
            suffix = '[]' if f.label == 3 else '?' if f.proto3_optional else ''
            output.append(f'{f.number}: {f.name}{suffix} {kind}')
        return '; '.join(output) or '(empty message)'

    lines = ['# Recovered action reference', '',
             'Generated by `python scripts/export_protocol_reference.py`. Build 107842.', '',
             'This inventories the protocol and explicit map-entry selectors across 98 shipped modules. Each selector has a reviewed handler rule and stated runtime requirements. It is not a context-free list of every possible simulation outcome. See [RECOVERY_STATUS.md](RECOVERY_STATUS.md).', '',
             '## Network actions', '',
             'All variants can be decoded, including empty messages. Message options are recovered metadata, not a claim that all variants appear in ordinary replays. The writer skips heartbeat and consults message options before recording.', '',
             '| Tag | Action | Fields | Options | Native writer filter |', '|---:|---|---|---|---|']
    for f in sorted(messages['NetAction'].field, key=lambda f: f.number):
        m = messages[f.type_name.rsplit('.', 1)[-1]]
        option_flags = flags(m)
        disposition = 'Excluded: heartbeat' if f.number == 2 else 'Excluded: ephemeral' if 'ephemeralNetAction' in option_flags else 'Not excluded by this filter'
        lines.append(f'| {f.number} | {f.name} | {fields(m)} | {option_flags} | {disposition} |')
    lines += ['', '## Participant actions', '',
              'Field 1 is participantId, distinct from router clientID and footer playerNumber. The action is a oneof.', '',
              '| Tag | Action | Fields |', '|---:|---|---|']
    for f in messages['NaParticipantAction'].field:
        if f.type_name:
            lines.append(f'| {f.number} | {f.name} | {fields(messages[f.type_name.rsplit(".", 1)[-1]])} |')
    lines += ['', '## Map dispatcher', '',
              '65 shared selectors plus the exported-entrypoint selector 4279446118. Every module has the same explicit selector sets, independently checked in C and WAT. The detailed handler review uses Ashen Boneyard as the reference. These include engine callbacks, not just player buttons. Retained names are matched to shipped strings; descriptive labels do not assert an original spelling.', '',
              '| Verb | Descriptive label | Retained source name | Payload mode | Reference C line |', '|---:|---|---|---|---:|']
    for key, value in load_catalog()['mapVerbs'].items():
        lines.append(f'| {key} | {value["name"]} | {value.get("sourceName", "Not retained; label only")} | {value["payloadMode"]} | {value["sourceCLine"]} |')
    lines += ['', '### Branch behavior and remaining requirements', '']
    for key,value in load_catalog()['mapVerbs'].items():
        lines += [f'#### {key}: {value["name"]}', '', value['behavior'], '',
                  f'Evidence: {value["evidence"]}.', '',
                  'Required to determine an actual outcome: '+ '; '.join(value['requires'])+'.', '']
    corpus = load_catalog_corpus()
    lines += ['## Exact map catalogs', '',
              'Counts are defined ability-command array slots (indices 0..29), repeated across maps. They are not unique action types, accessible buttons, or successful executions. Empty/disabled targets remain in the definitions.', '',
              '| Map | Runtime hash | Archetypes | Defined command slots |', '|---|---|---:|---:|']
    for key,value in sorted(corpus['maps'].items(),key=lambda pair:pair[1]['map']):
        lines.append(f'| {value["map"]} | {key} | {value["archetypeCount"]} | {value["definedAbilityCommandSlots"]} |')
    lines += ['', '## Nested fields', '', 'Optional presence is retained. Signed coordinates use the matching SDK scale of 16,384.', '']
    for name, m in messages.items():
        if name.startswith(('Na', 'Pa')) or name in ('Vector2', 'SPRecordingFooter', 'SPRecordingPlayerData', 'PlayerSlotSpec', 'ResultSnapshot', 'PlayerResultSnapshot', 'GlobalResultSnapshot'):
            lines += [f'### {name}', '', fields(m), '']
    (ROOT / 'docs').mkdir(exist_ok=True)
    (ROOT / 'docs/ACTIONS.md').write_text('\n'.join(lines).rstrip() + '\n', encoding='utf-8')
    print(f'{len(messages["NetAction"].field)} network variants; 7 participant variants; 66 map selectors; {len(corpus["maps"])} catalogs')


if __name__ == '__main__':
    generate()
