"""Generate the action reference from bundled descriptors and map metadata."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from google.protobuf import descriptor_pb2
from recovered_replay import SCHEMA, load_catalog, varint


def generate():
    schema = descriptor_pb2.FileDescriptorProto()
    schema.ParseFromString(SCHEMA.read_bytes())
    messages = {m.name: m for m in schema.message_type}
    extensions = {e.number: e.name for e in schema.extension}

    def flags(message):
        raw, pos, result = message.options.SerializeToString(), 0, []
        while pos < len(raw):
            key, pos = varint(raw, pos)
            if key & 7:
                raise ValueError('Unexpected option wire type')
            value, pos = varint(raw, pos)
            if value:
                result.append(extensions.get(key >> 3, str(key >> 3)))
        return ', '.join(result)

    def fields(message):
        output = []
        for f in message.field:
            kind = f.type_name.rsplit('.', 1)[-1] if f.type_name else descriptor_pb2.FieldDescriptorProto.Type.Name(f.type).removeprefix('TYPE_').lower()
            suffix = '[]' if f.label == 3 else '?' if f.proto3_optional else ''
            output.append(f'{f.number}: {f.name}{suffix} {kind}')
        return '; '.join(output) or '(empty message)'

    lines = ['# Recovered action reference', '',
             'Generated by `python scripts/export_protocol_reference.py`. Build 107842.', '',
             'This is the protocol and matching Ashen Boneyard dispatch surface, not every simulation outcome. Custom maps can add verbs. Unknown values are preserved.', '',
             '## Network actions', '',
             'All variants can be decoded, including empty messages. Message options are recovered metadata, not a claim that all variants appear in ordinary replays. The writer skips heartbeat and consults message options before recording.', '',
             '| Tag | Action | Fields | Options |', '|---:|---|---|---|']
    for f in sorted(messages['NetAction'].field, key=lambda f: f.number):
        m = messages[f.type_name.rsplit('.', 1)[-1]]
        lines.append(f'| {f.number} | {f.name} | {fields(m)} | {flags(m)} |')
    lines += ['', '## Participant actions', '',
              'Field 1 is participantId, distinct from router clientID and footer playerNumber. The action is a oneof.', '',
              '| Tag | Action | Fields |', '|---:|---|---|']
    for f in messages['NaParticipantAction'].field:
        if f.type_name:
            lines.append(f'| {f.number} | {f.name} | {fields(messages[f.type_name.rsplit(".", 1)[-1]])} |')
    lines += ['', '## Map dispatcher', '',
              'All 65 explicit verb comparisons in the matching on_action_shared function, including system callbacks. These are not 65 player buttons. Handler-derived labels describe behavior, not original enum spelling. Unnamed branches remain unresolved.', '',
              '| Verb | Name / handler label | Evidence status | Generated C line |', '|---:|---|---|---:|']
    for key, value in load_catalog()['mapVerbs'].items():
        lines.append(f'| {key} | {value["name"] or "Unresolved handler"} | {value["status"]} | {value["dispatchLine"]} |')
    lines += ['', '## Nested fields', '', 'Optional presence is retained. Signed coordinates use the matching SDK scale of 16,384.', '']
    for name, m in messages.items():
        if name.startswith(('Na', 'Pa')) or name in ('Vector2', 'SPRecordingFooter', 'SPRecordingPlayerData', 'PlayerSlotSpec', 'ResultSnapshot', 'PlayerResultSnapshot', 'GlobalResultSnapshot'):
            lines += [f'### {name}', '', fields(m), '']
    (ROOT / 'docs').mkdir(exist_ok=True)
    (ROOT / 'docs/ACTIONS.md').write_text('\n'.join(lines).rstrip() + '\n', encoding='utf-8')
    print(f'{len(messages["NetAction"].field)} network variants; 7 participant variants; 65 map comparisons')


if __name__ == '__main__':
    generate()
